### ISSUE TITLE
Hello. Doesn't connect to 3commas. How to solve this error?

### ISSUE THREAD

**Issue by ketlller** [MarcDrexler/3Commas.BulkEditor#29]
Doesn't connect to 3commas. How to solve this error?
Windows 7 (64)

18.02.2021 2:17:59 Information: Retrieving bots from 3Commas...
18.02.2021 2:17:59 Error: An error occurred: 3Commas Connection Issue: Error getting response from server: System.Net.Http.HttpRequestException:  An error occurred while sending your request. ---> System.Net.WebException: The request was aborted: Failed to create SSL / TLS secure channel.
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
--- End of trace of the internal exception stack ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at XCommas.Net.XCommasApi.d__106.MoveNext()

**Comment by MarcDrexler** [comment]
Hi, please have a look at #12
