### ISSUE TITLE
How do I create a secure SSL / TLS channel?

### ISSUE THREAD

**Issue by ketlller** [MarcDrexler/3Commas.BulkEditor#31]
Hi,
I have windows 7 (64) and .NET Framework 4.7.2 installed

An error occurred while sending the request.
Doesn't connect to 3Commas.

Errors:
21.02.2021 3:10:31 Information: Retrieving deals from 3Commas...
21.02.2021 3:10:31 Error: An error occurred: 3Commas Connection Issue: Error getting response from server: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XCommas.Net.XCommasApi.<GetRawResponse>d__106.MoveNext()

My questions are:

How do I create a secure SSL / TLS channel?

Thank you!

![image](https://user-images.githubusercontent.com/29217050/108612893-3f3bd680-73f5-11eb-9be1-7317f14d9c87.png)

**Comment by ketlller** [comment]
> Hi,
> I have windows 7 (64) and .NET Framework 4.7.2 installed
> 
> An error occurred while sending the request.
> Doesn't connect to 3Commas.
> 
> Errors:
> 21.02.2021 3:10:31 Information: Retrieving deals from 3Commas...
> 21.02.2021 3:10:31 Error: An error occurred: 3Commas Connection Issue: Error getting response from server: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
> at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
> at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
> --- End of inner exception stack trace ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at XCommas.Net.XCommasApi.d__106.MoveNext()
> 
> My questions are:
> 
> How do I create a secure SSL / TLS channel?
> 
> Thank you!
> 
> ![image](https://user-images.githubusercontent.com/29217050/108612893-3f3bd680-73f5-11eb-9be1-7317f14d9c87.png)
