### ISSUE TITLE
Help solve the problem, do not delete my question please - How do I create a secure SSL / TLS channel? 

### ISSUE THREAD

**Issue by ketlller** [MarcDrexler/3Commas.BulkEditor#32]
Hi,
What Windows will your program run on?

I have windows 7 (64) and .NET Framework 4.7.2 installed

An error occurred while sending the request.
Doesn't connect to 3Commas.

Errors:
21.02.2021 3:10:31 Information: Retrieving deals from 3Commas...
21.02.2021 3:10:31 Error: An error occurred: 3Commas Connection Issue: Error getting response from server: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
--- End of inner exception stack trace ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at XCommas.Net.XCommasApi.d__106.MoveNext()

My questions are:

How do I create a secure SSL / TLS channel?

Thank you!

![image](https://user-images.githubusercontent.com/29217050/108614904-63a0ae80-7407-11eb-90c5-61abf2724ac4.png)

**Comment by MarcDrexler** [comment]
Hi,

Don't worry, I'm not just going to delete questions without answering them. But I've marked your previous questions as duplicates with a link to the answer. You can still answer closed questions.

Please read my [answer](https://github.com/MarcDrexler/3Commas.BulkEditor/issues/12#issuecomment-720983215) carefully.

Most current web servers prefer TLS 1.3 and TLS 1.2. Sometimes TLS 1.1 and TLS 1.0 are still supported, but not here and I can't do much about it 😞

**Comment by ketlller** [comment]
Hi Marc.

the program will not work on windows 7?  Need to install Windows 10 only?




Вс, 21 февр. 2021 г. в 10:14, Marc <notifications@github.com>:

**Comment by MarcDrexler** [comment]
You can try [this](https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392) and maybe it works for you on Windows 7.
