### ISSUE TITLE
Error loading DCA bots

### ISSUE THREAD

**Issue by SwampTrader** [MarcDrexler/3Commas.BulkEditor#56]
First time user...
My Grid Bots loaded in ok, but none of the DCA bots loaded. I get the following error:
**12-Jun-21 6:00:12 PM Error: An error occurred: Problem with 3Commas connection (Account: 'xxxx'): Could not serialize json to Bot[] : Newtonsoft.Json.JsonSerializationException: Error converting value "BB-20-2-UB" to type 'XCommas.Net.Objects.TaPresetsType'. Path '[1].options.type', line 1, position 8843. ---> System.ArgumentException: Requested value 'BB-20-2-UB' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---**
All my DCS use either the BB-20-1-UB, BB-20-2-UB, BB-20-1-LB or BB-20-2-LB, so i guess the script is having trouble with that particular Json setting?

**Comment by SwampTrader** [comment]
I checked loading my paper account, that also has similar TAPreset using BB-20-2-UB, and it loads ok with no errors.
